MinecraftForge/Documentation

conventions/versioning.md
I know @unascribed (see #12) also has a version section in his pull request, but this is an idea we (with the help of @PaleoCrafter) came up with. It's basically a modified version of Semantic Versioning, which allows for easier MC version spotting as well as changing versions for API changes that don't break the world. Any feedback is appreciated.
=> Versioning conventions using alternative Semantic

blockstates/forgeBlockstates.md, blockstates/introduction.md
I don't have a local setup to test if the enumeration is actually fixed, if you please would, tterrag. Weirdly enough it worked fine in the online editor I tested it with.
For documentation purposes: The issue is that the enumeration is interpreted as *foo* and therefore converted into multiple italic parts. If this doesn't fix it, then the line-endings are probably incorrect.
=> Blockstates: Add Lex' remarks and fix the enumeration

docs/conventions/versioning.md
Using + for lists does not seem universally accepted. Lists using - and * are definitely always correct, so
use those instead.
=> Fix list in versioning docs

docs/css/code_fixer.css
In addition to support for multiline code blocks in admonitions, the blocks also have a padding now. This should have actually always been the case, the padding wasn't applied due to the 'code' tags being inline elements, though. Last but not least, paragraphs within an admonition have a smaller bottom margin, making the entire design a little more compact.
=> Fix admonition CSS

docs/conventions/locations.md
All file types except `mcmod.info` go in the `assets/<modid>` folder rather than the root `src/main/resources/` folder.
=> Fix paths in locations.md

mkdocs.yml
The rationale behind this is that these are core concepts that you must read before basically anything else, so it makes sense for it to actually be near the top.
=> Move the Concepts category up in the list

docs/datastorage/capabilities.md
Since World Capabilities are not recommended for universal data access for world, this small change would be sufficient.
=> Added AttachCapabilityEvent.World.

docs/utilities/oredictionary.md, mkdocs.yml
Added section describing how to use the OreDictionary, including name conventions and a short list of  common OreDictionary prefixes and suffixes.
Also added the Utilities category to mkdocs.yml, positioned between the Data Storage and Effects categories.
=> Add Utilities category and OreDictionary sub-category

docs/blocks/blocks.md, docs/concepts/registries.md, docs/effects/sounds.md, mkdocs.yml
Document what registries are, what they do, how to create them, and how to register objects to them. Also document the new registry events as the preferred method of registering objects.
Update other pages to refer to the new page when referring to registration.
=> Document registry system

docs/concepts/registries.md
With the overhaul of the registry system in 1.12, registry events are now fired *after* preInit rather than before preInit; so this admonition is no longer required.
=> Remove outdated admonition on Registries page

docs/forgedev/index.md, docs/forgedev/prguidelines.md, mkdocs.yml
As per @mezz's request, I wrote down a guide on how to set up a Forge development environment and I included his PR guidelines ([see forum](http://www.minecraftforge.net/forum/index.php?topic=43579.0)).
The guide currently only covers the setup for IntelliJ IDEA based on cpw's [video](https://www.youtube.com/watch?v=yanCpy8p2ZE). Hence, this PR is to be considered WIP.
ToDo list:
=> Guide on Forge contribution

docs/networking/simpleimpl.md
Too many mods are vulnerable to arbitrary chunk generation due to insecure packet handling. I feel defensive packet handling deserves to be mentioned in the documentation.
I kind of want to write "Never trust the client", but I don't want it too be pushy and it feels a bit out of scope. Thoughts?
=> SimpleImpl: Add warning about insecure handling of packets on the server

docs/concepts/registries.md, docs/conventions/loadstages.md
Given that it is now "recommended and HIGHLY encouraged" to use RegistryEvents over registering during loading events, I thought it might be helpful to list which objects can be registered using RegistryEvents. I also added a link to the Loading Stages page to encourage modders not to continue doing their registrations there. In response to #85, I also included a bit of information around why RegistryEvents should be preferred.
Not having an in-depth knowledge of the inner-workings or direction motivations of Forge itself, if anything I've added is incorrect I'm happy to make changes.
=> Documented available RegistryEvents

docs/networking/simpleimpl.md
- Uses an anonymous implementation of `Runnable()` and adds it via `addScheduledTask()` to prevent threading errors
- Updates the warning block to indicate the changes
- Changes `Items.diamond` to its correct name, `Items.DIAMOND`
**Justification**: What is the point of doing something incorrectly just to correct it a few lines down? Docs should show only the correct implementations as examples.
**_Side question_**: Should the documentation use an anonymous `Runnable` implementing class (as is used with this PR) or with a _block lambda expression_? (**lines 65-70** would instead read as follows)
```java
serverPlayer.getServerWorld().addScheduledTask(() -> {
serverPlayer.inventory.addItemStackToInventory(new ItemStack(Items.DIAMOND, amount));
});
```
=> Correct example MessageHandler to use addScheduledTask(...)

docs/gettingstarted/structuring.md
On line 34 of `structuring.md` there was a misplaced comma. This mistake would cause the mcmod.info to fail parsing during game load.
=> Fixed a small error w/ `mcmod.info` example

docs/forgedev/index.md
In a discussion on a Discord server, somebody noted that the test output directory does in fact not exist before the project was built at least once. As I was working with an existing workspace when writing the guide, I did not notice that. This PR adds an initial build as the first step to the test mod section.
=> Correct Forge Dev setup guide

docs/gettingstarted/index.md
There is no `gradlew.sh`, at least not in the latest mdk (and AFAIK the gradle wrapper script for *nix never had a file extension), the files the docs refer to here are `gradlew.bat` (for Windows) and simply `gradlew` (for anybody else). I think it reduces friction for people unfamiliar with gradle to just explicitly spell out the names of both files and not mention a `.sh` file name extension that does not exist.
=> Reduce confusion regarding gradle wrapper scripts

docs/conventions/locations.md
This'll do until 1.13 when we have to rewrite this for the new json format, anyways.
Solves #124, #137, and #148
=> Add a note about lang file names with pack_format 3

docs/gettingstarted/dependencymanagement.md, mkdocs.yml
Based on what was introduced in this PR https://github.com/MinecraftForge/MinecraftForge/pull/4841. This is mostly about the dependency extraction part, but also adds a necessary introduction to repositories.
Requesting review from @LexManos on this one. A specific thing I could use feedback on is the name "The mod repository". That is what I have called the repository where contained dependencies are archived. Is there perhaps a better name? I also deliberately chose to not document the deprecated behavior, namely placing contained dependencies in the jar root and not specifying the Maven-Artifact manifest attribute.
=> Add Dependency Management page

docs/models/advanced/extended-blockstates.md
This merges the second half of #152 into the existing extended state article (replacing the usage example that was already there). I found the first half pretty good so I'm keeping it over my first half.
=> Merge my extended state doc into existing one

forge_theme/base.html, forge_theme/nav.html, forge_theme/search.html, mkdocs.yml
This fixes #171. Read the Docs appears to have updated their build scripts to use mkdocs version 17.x at some point in the last few weeks. The new version introduced changes to theme building that needed to be addressed.
While testing out the new build, I'd also noticed the (admittedly weird) FontAwesome JS solution to not work reliably, so I also changed that to use CSS.
It looks like RTD heavily wants to push its default themes. They even override the `theme.custom_dir` option which is the correct way to define a theme directory in the new versions of mkdocs, while the old `theme_dir` is deprecated, yet still supported by RTD. If RTD updates to a version of mkdocs that removes `theme_dir`, chances are our custom theme won't work at all anymore.
=> Update Forge Theme for mkdocs v17

README.md, docs/conventions/versioning.md, docs/effects/sounds.md, docs/gettingstarted/autoupdate.md, docs/gettingstarted/index.md, docs/gettingstarted/structuring.md, docs/index.md, docs/items/loot_tables.md, docs/models/blockstates/introduction.md, docs/models/color.md, docs/models/files.md, docs/models/overrides.md, docs/networking/index.md, forge_theme/base.html
There were a bunch of links using HTTP to sites that supported HTTPS, so I changed all of them to use HTTPS. Of course, some sites only supported HTTP, so I did not change those.
I also fixed some trailing spaces… or rather, my editor fixed them, and then I noticed it while submitting this PR. So hooray for bonus fixes, I guess? :stuck_out_tongue:
=> Update links from HTTP to HTTPS where possible

docs/utilities/oredictionary.md
This pull request:
* Changes `oredictionary.md`, so it uses recipe json as example. Thus this closes #181.
* Changes `oredictionary.md`, so it points to `recipes.md` as further reading.
=> Close #181: Update OreDict page

docs/utilities/recipes.md
Changed "diamond" and "minecraft:diamond" to "gemDiamond", as that's what their mappings are in the actual OreDictionary. Alleviates some confusion people may have (myself included), and also exposes some good naming practices for OreDictionary entries.
=> Fixed misleading ore_dict ore names

docs/networking/entities.md, mkdocs.yml
Quick overview of the vanilla datasync system, plus a bit about Forge's spawn packet handling.
Includes the obligatory "don't do this" warning about registering data parameters wrongly.
=> Basic entity sync documentation
