Networking/SimpleImpl/index.md
Documents how to make IMessage packets, IMessageHandler classes, and how to send the packets.
=> Add SimpleImpl page

mkdocs.yml
The yml file will need to be updated as pages are added, it can control the order and "proper" name of every file.
=> Add mkdocs.yml, fixes section display names

networking/simpleimpl.md
=> Change name of message class from 'Packet' to 'MyMessage'

networking/overview.md
The numbered list was not displaying properly
=> Update formatting to work with markdown

docs/conventions/locations.md
=> Fixed some incorrect spelling

docs/gettingstarted/index.md
This is an error which occurs even if user goes step by step through current documentation so information about it should be included
=> Added information about GC overhead limit exceeded error

docs/datastorage/capabilities.md, docs/datastorage/extendedentityproperties.md, docs/datastorage/worldsaveddata.md, mkdocs.yml
As the title says, I added straightforward and to the point explanations of the IEEP and WorldSavedData systems, along with skeleton examples of both.
=> Explanations for the different data attaching/storage systems.

docs/concepts/sides.md, mkdocs.yml
Not sure if this is the clearest way this can be said, but I think it cleans up a lot of misconceptions about when to use the various sided mechanisms available to us.
=> Preliminary article on sides

docs/blockstates/forgeBlockstates.md, docs/blockstates/introduction.md, docs/concepts/sides.md, docs/conventions/locations.md, docs/conventions/versioning.md, docs/datastorage/capabilities.md, docs/datastorage/extendedentityproperties.md, docs/datastorage/worldsaveddata.md, docs/gettingstarted/index.md, docs/gettingstarted/structuring.md, docs/networking/index.md, docs/networking/overview.md, docs/networking/simpleimpl.md
There are too many formatting issues in the docs. Here is a bulk fix for them
=> Fix & clean up formatting in the docs

docs/blockstates/states.md, mkdocs.yml
Add to mkdocs.yml
Add missing newline in states.md
=> Fix states PR

docs/blockstates/states.md, docs/concepts/sides.md
* Change sketchy proxy part in sides.md
* Overhaul states.md because reading it through as someone with no experience with states at all, it all seems very very hand wavey - no or unclear explanations about why things are the way they are. Hopefully this is better
=> Updates to my articles

docs/gettingstarted/autoupdate.md, mkdocs.yml
=> Added doc for version checker

docs/datastorage/capabilities.md
Added brief description of the IFluidHandler capability.
=> Updated Capabilities page

docs/blocks/blocks.md
Add note about registering `ItemBlock`s as well as registering `Block`s, and note that `GameRegistry.registerWithItem` should not be used.
=> Add note about `ItemBlocks` in blocks/blocks.md

docs/gettingstarted/structuring.md
Define what it is, what it does, and what it can define.
=> Add `mcmod.info` to gettingstarted/structuring.md

docs/datastorage/worldsaveddata.md
The method was renamed in response to ModCoderPack/MCPBot-Issues#247.
=> Update method name in worldsaveddata.md

docs/events/intro.md
Also format the headers to comply with the style guide.
=> Add sections on static event handlers and `@EventBusSubscriber` to Events page

docs/blockstates/introduction.md
I ran into this issue because there was no documentation on it. Hopefully this will save someone else the pain I endured trying to figure this out. :)
=> Add Information about Vanilla Blockstates

docs/blockstates/states.md
This can cause things like Vazkii/Botania#1999 to happen if you don't do this check
Vanilla does this check in the flower pot itself
=> Add warning about actual states and TE's

docs/items/items.md, mkdocs.yml
Add category and base page in that category for items analogous to the "Blocks" category.
=> Add Items category

docs/items/loot_tables.md, mkdocs.yml
Still have one section missing, but throwing this up here for now
=> Article for loot tables

docs/events/intro.md
This commit modifies the documentation on FML events as to match the changes made in MinecraftForge/MinecraftForge#3926
=> Update Event Documentation To Match MinecraftForge/MinecraftForge#3926

docs/concepts/registries.md
Move some of the lower level stuff out of the intro section.
Link to "Events" page.
=> Make "Registries" page more beginner friendly

docs/datastorage/capabilities.md
Furthermore, I might work on making the Capabilities more implementation-focused, as it is slightly unclear on what is required for different implementations/use-cases (it kind-of just throws everything at you at once).
=> Quick typo fix

docs/blocks/interaction.md
#94 : Added documentation about the `onBlockClicked` block interaction method.
=> #94: interaction documentation for onBlockClicked

docs/datastorage/capabilities.md
https://github.com/MinecraftForge/MinecraftForge/pull/4228
Also added a little warning about marking chunks as dirty for state changes.
=> Chunk capabilities

docs/datastorage/capabilities.md
The event is AttachCapabilitiesEvent, not AttachCapabilityEvent.
=> Fix incorrect event name

docs/config/@config.md, mkdocs.yml
=> Adds Config.md

docs/gettingstarted/autoupdate.md
Remake of #82 since my branch disappeared. all comments addressed.
=> Add section on checking update result from code

docs/blocks/interaction.md
#94 : Added documentation about the `onBlockDestroyedByPlayer` interaction method.
=> #94: interaction documentation for onBlockDestroyedByPlayer

docs/gettingstarted/index.md
Replace non-breaking spaces screwing up formatting in getting started.
=> Replace non-breaking spaces screwing up formatting

mkdocs.yml
#155 didn't add the page to the index 👏 👏 👏
=> Add TEISR page to index

docs/utilities/permissionapi.md, mkdocs.yml
Added a new Page for the mostly unknown PermissionAPI forge provides.
Might contain a few typos and or grammar errors, would be nice if someone could take a look at it.
=> Added new Page for the PermissionAPI

docs/concepts/registries.md
Superfences should add support nested admonitions.
But I am not sure if the Forge Design supports them properly.
=> Fixes #169.

docs/gettingstarted/debugprofiler.md, mkdocs.yml
This is a section explaining vanillas build in Debug Profiler and how Modders can utilize it.
=> Added a Section for the Debug Profiler

docs/concepts/internationalization.md, mkdocs.yml
I see lots of confusion about localization, and often see it used incorrectly. Documenting it should hopefully help.
=> Add internationalization and localization page

docs/config/annotations.md
Fairly certain this is an error
=> Fix RequiresWorldRestart in Config

docs/models/advanced/ibakedmodel.md, docs/models/advanced/itemoverridelist.md
- Fix broken link in ItemOverrideList page
- Update docs of `isBuiltinRenderer`, so it points to the TEISR page
=> Minor fixes

docs/networking/entities.md, docs/networking/simpleimpl.md
* Clean up entity page, removing old refs and updating mcp names
* Rewrite simpleimpl page for new system
=> Update Networking section

docs/forgedev/index.md
The task name 'setupForge' changed to 'setup'
=> Task name update

docs/gettingstarted/index.md
"its" is possessive, "it's" is a contraction
=> Grammar Issue
